name: Deploy to Render
on:
  push:
    branches: [main, master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render
        run: |
          curl -X POST "https://api.render.com/deploy/srv-d36pnp2dbo4c73dv89o0?key=AnDLZn1zmGA"